name: LuckPermsGUI
main: me.AsVaidas.LuckPemsGUI.Main
version: 3.0
author: BGHDDevelopment
depend: [LuckPerms]
permissions:
  luckperms.gui:
    description: GUI LuckPerms
    default: op
commands:
   lpgui:
      description: Opens LuckPerms GUI
      usage: /<command>