name: LuckPermsGUI
main: com.bghddevelopment.LuckPemsGUI.LuckPermsGUI
version: 4.6
author: BGHDDevelopmentLLC
website: https://bghddevelopment.com
depend: [LuckPerms]
permissions:
  luckperms.gui:
    description: GUI LuckPerms
    default: op
commands:
   lpgui:
      description: Opens LuckPerms GUI
      usage: /<command>