name: LuckPermsGUI
main: com.bghddevelopment.LuckPemsGUI.LuckPermsGUI
version: 4.5
author: BGHDDevelopmentLLC
website: https://bghddevelopment.com
depend: [LuckPerms]
api-version: 1.18
permissions:
  luckperms.gui:
    description: GUI LuckPerms
    default: op
commands:
   lpgui:
      description: Opens LuckPerms GUI
      usage: /<command>
